### ISSUE TITLE
Release to Hex?

### ISSUE THREAD

**Issue by voltone** [voltone/curve448_ex#1]
@mwmiller: I used your `curve25519_ex` library as the basis for a Curve448 DH library. Since the code is 99% yours, would you be interested in adding this lib to your collection of crypto libraries, and publishing it to Hex? I don't feel comfortable taking credit for it, and I'm not really qualified to maintain it anyway...

**Comment by mwmiller** [comment]
@voltone: I really should generalize that code a bit and make it possible to "plug in" various curves.  Regardless, I can spin up and handle the maintenance of a Curve448 library if you would like.  It will probably take me (at least) a couple days to handle all the requisite work, so do whatever is expedient in the meantime.

Thanks for looking!

**Comment by voltone** [comment]
@mwmiller: Great, thanks, appreciate it. No rush.

I would have added Curve448 to `curve25519_ex` as a PR if the library name hadn't been so specific. That might work if you were to rename the package to `rfc7748_ex`? Or `montgomery`? But then again, those names might limit discoverability in Hex...

**Comment by mwmiller** [comment]
I think [this](https://github.com/mwmiller/curve448_ex) resolves your issues.  It's still not perfectly namespaced, but hopefully will let you move along with your projects.

**Comment by voltone** [comment]
Awesome, thanks @mwmiller! I'll get back to my Noise Protocol implementation, which uses just about every one of your Elixir crypto libraries :)

**Comment by mwmiller** [comment]
@voltone:  Excellent.  Noise is very cool; I wish you well!  I might even want to build something on top of that.  Please do let me know if you run into annoying edges on the libraries.  It's probably clear they've been mostly built to scratch my own itches and certainly haven't been tuned for performance.

**Comment by voltone** [comment]
@mwmiller same here: I'm not too concerned with raw performance at the moment, I'm doing this mostly as a learning exercise. That's why I prefer your pure-Elixir implementations over some wrapper around a C library: it gives me better visibility into how all the pieces work together. I'll let you know how it works out
